# Generated by Django 5.0.1 on 2025-09-26 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleDriveFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_id",
                    models.CharField(
                        help_text="Google Drive folder ID", max_length=255, unique=True
                    ),
                ),
                (
                    "folder_name",
                    models.CharField(
                        help_text="Google Drive folder name", max_length=255
                    ),
                ),
                (
                    "owner_email",
                    models.EmailField(
                        help_text="Email of the folder owner", max_length=254
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_validated",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this folder was validated",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this folder is actively being monitored",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who has access to this folder",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_drive_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Drive Folder",
                "verbose_name_plural": "Google Drive Folders",
                "db_table": "api_google_drive_folders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoogleDriveWatchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("file_added", "File Added"),
                            ("file_removed", "File Removed"),
                            ("file_modified", "File Modified"),
                            ("all", "All Changes"),
                        ],
                        default="all",
                        help_text="Type of changes to watch for",
                        max_length=20,
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL to send notifications to",
                        null=True,
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Whether to send email notifications"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this watch configuration is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Drive API resource ID for the watch",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True, help_text="When the watch expires", null=True
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="Google Drive folder being watched",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_configs",
                        to="api.googledrivefolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this watch configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_watch_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Drive Watch Configuration",
                "verbose_name_plural": "Google Drive Watch Configurations",
                "db_table": "api_google_drive_watch_configs",
                "ordering": ["-created_at"],
                "unique_together": {("folder", "user")},
            },
        ),
    ]
