# Generated by Django 5.0.1 on 2025-09-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_ingestionrun_bookingconflict_processedfile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="car_rego",
            field=models.CharField(
                blank=True, help_text="Car registration", max_length=100
            ),
        ),
    ]
