# Generated by Django 5.0.1 on 2025-09-27 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_booking_car_rego"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="googledrivefolder",
            name="folder_id",
            field=models.CharField(help_text="Google Drive folder ID", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="googledrivefolder",
            unique_together={("folder_id", "user")},
        ),
    ]
