# Generated by Django 5.0.1 on 2025-09-28 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_allow_shared_folders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                help_text="User who imported this booking data",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_number",
            field=models.CharField(
                help_text="Booking number (e.g., 214078)", max_length=50
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("booking_number", "user")},
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["user"], name="api_booking_user_id_340ce1_idx"),
        ),
    ]
