# Generated by Django 5.0.1 on 2025-09-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedfile",
            name="file_id",
            field=models.CharField(help_text="Google Drive file ID", max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="processedfile",
            unique_together={("file_id", "folder")},
        ),
    ]
