# Generated by Django 5.0.1 on 2025-11-02 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="PatientQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gender_other",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("has_mhcp", models.BooleanField(default=False)),
                (
                    "mhcp_file",
                    models.FileField(blank=True, null=True, upload_to="mhcp_files/"),
                ),
                (
                    "sexual_orientation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "relationship_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("religion", models.CharField(blank=True, max_length=50, null=True)),
                ("is_spiritual", models.BooleanField(blank=True, null=True)),
                ("has_therapy_history", models.BooleanField(blank=True, null=True)),
                ("is_employed", models.BooleanField(blank=True, null=True)),
                (
                    "financial_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Questionnaire",
                "verbose_name_plural": "Patient Questionnaires",
                "db_table": "patient_questionnaires",
                "ordering": ["-created_at"],
            },
        ),
    ]
